const htmlContent = """
<div>
        <p>FACEBANK INTERNATIONAL CORPORATION

DIVULGACIONES Y TERMINOS DE LAS CUENTAS DE DEPÓSITO

 INFORMACIÓN IMPORTANTE SOBRE PROCEDIMIENTOS PARA LA APERTURA DE UNA CUENTA NUEVA.

 La ley federal (Estados Unidos) le requiere a las instituciones financieras que obtengan, cotejen y mantengan récord de la información que identifica a cada persona que establece una cuenta ya fuere de depósito o de crédito en la institución. Esto con el propósito de ayudar al gobierno a evitar el financiamiento del  terrorismo y las actividades de lavado de dinero. Que significa esto para usted: cuando usted abra una cuenta, nosotros  le  preguntaremos su nombre, dirección, fecha de nacimiento, y otra información que nos permita identificarlo a usted.  Dicho procedimiento será de aplicación  tanto en la apertura de una Cuenta de Depósito o Crédito como en cualquier otro tipo de cuenta que se establezca en el Banco. Nosotros también podremos solicitar ver su licencia de conducir o Cédula de Identidad o Pasaporte y  la de su representante  u otros documentos de identificación.  El Banco se reserva la facultad de requerir cualquier documento pertinente a la identidad  del titular de la Cuenta, la identidad de las firmas autorizadas y/o la procedencia de los fondos y/o de sus ingresos. El Depositante y/o las firmas autorizadas en la Cuenta, se comprometen a presentar, a solicitud del Banco, evidencia sobre su ocupación, sus fuentes de ingresos personales, de la persona jurídica y/o negocio a beneficio de quien se establece la Cuenta, licencias, permisos y la procedencia o naturaleza de los fondos a depositar en una Cuenta o repago del crédito concedido, entre otra información. Se obliga además a brindar información sobre sus referencias con otras instituciones depositarias.  El (los) suscribiente(s)  acuerda(n) producir un documento que le(s) identifique, con su firma, foto y número de seguro social o cédula de identidad  y/o cualquier otro documento adicional solicitado por el Banco para verificar la identidad del (los) suscribiente(s). El (los) suscribiente(s) se comprometen a presentar, a solicitud del Banco evidencia sobre su ocupación, su fuente de ingresos  y/o la procedencia o naturaleza de los fondos que se utilizarán para el repago de la obligación financiera. Se obliga además a brindar información sobre sus referencias con otras instituciones depositarias. </p>
      </div>
""";
